<a href="https://colab.research.google.com/github/humamkhan2k/Access_Denied/blob/master/Access_Denied.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np 

# data processing
import pandas as pd 

# data visualization
import seaborn as sns
%matplotlib inline
from matplotlib import pyplot as plt
from matplotlib import style

# Algorithms
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.naive_bayes import GaussianNB
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, validation_curve, learning_curve
from sklearn.cluster import KMeans
from sklearn import metrics
from xgboost import XGBClassifier
from sklearn.neural_network import MLPClassifier
from google.colab import files

In [0]:
url1 = 'https://raw.githubusercontent.com/humamkhan2k/Access_Denied/master/development_dataset.csv'
url2 = 'https://raw.githubusercontent.com/humamkhan2k/Access_Denied/master/leaderboard_dataset.csv'
url3 = 'https://raw.githubusercontent.com/humamkhan2k/Access_Denied/master/Evaluation_dataset.csv'
train_df = pd.read_csv(url1)
lead_df = pd.read_csv(url2)
eval_df = pd.read_csv(url3)

In [0]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34000 entries, 0 to 33999
Data columns (total 21 columns):
VAR1     34000 non-null int64
VAR2     33039 non-null float64
VAR3     30615 non-null float64
VAR4     21506 non-null float64
VAR5     33999 non-null float64
VAR6     30505 non-null float64
VAR7     33165 non-null float64
VAR8     33165 non-null float64
VAR9     18183 non-null float64
VAR10    29450 non-null float64
VAR11    26435 non-null float64
VAR12    23498 non-null float64
VAR13    25478 non-null float64
VAR14    34000 non-null object
VAR15    25976 non-null float64
VAR16    33134 non-null float64
VAR17    11806 non-null float64
VAR18    34000 non-null int64
VAR19    34000 non-null int64
VAR20    34000 non-null float64
VAR21    34000 non-null object
dtypes: float64(16), int64(3), object(2)
memory usage: 5.4+ MB

In [0]:
train_df.describe()

               VAR1          VAR2  ...         VAR19         VAR20
count  34000.000000  33039.000000  ...  34000.000000  34000.000000
mean   17000.500000    917.391603  ...      0.298059    161.355950
std     9815.098913     50.222389  ...      0.457412    123.231136
min        1.000000    730.588235  ...      0.000000      0.000000
25%     8500.750000    882.352941  ...      0.000000    104.385542
50%    17000.500000    924.705882  ...      0.000000    117.493115
75%    25500.250000    956.470588  ...      1.000000    159.446213
max    34000.000000   1000.000000  ...      1.000000   1000.000000

[8 rows x 19 columns]

In [0]:
total = train_df.isnull().sum().sort_values(ascending=False)
percent_1 = train_df.isnull().sum()/train_df.isnull().count()*100
percent_2 = (round(percent_1, 1)).sort_values(ascending=False)
missing_data = pd.concat([total, percent_2], axis=1, keys=['Total', '%'])
missing_data

       Total     %
VAR17  22194  65.3
VAR9   15817  46.5
VAR4   12494  36.7
VAR12  10502  30.9
VAR13   8522  25.1
VAR15   8024  23.6
VAR11   7565  22.2
VAR10   4550  13.4
VAR6    3495  10.3
VAR3    3385  10.0
VAR2     961   2.8
VAR16    866   2.5
VAR8     835   2.5
VAR7     835   2.5
VAR5       1   0.0
VAR21      0   0.0
VAR20      0   0.0
VAR14      0   0.0
VAR18      0   0.0
VAR19      0   0.0
VAR1       0   0.0

In [0]:
train_df.groupby(['VAR21'])

In [0]:
# train_df = train_df.drop(['VAR1','VAR17','VAR9','VAR4','VAR12'], axis=1)

In [0]:
# data = [train_df, test_df]

# for dataset in data:
#     mean10 = train_df["VAR10"].mean()
#     mean11 = train_df["VAR11"].mean()
#     mean13 = train_df["VAR13"].mean()
#     mean15 = train_df["VAR15"].mean()
#     std10 = test_df["VAR10"].std()
#     std11 = test_df["VAR11"].std()
#     std13 = test_df["VAR13"].std()
#     std15 = test_df["VAR15"].std()
#     is_null10 = dataset["VAR10"].isnull().sum()
#     is_null11 = dataset["VAR11"].isnull().sum()
#     is_null13 = dataset["VAR13"].isnull().sum()
#     is_null15 = dataset["VAR15"].isnull().sum()
#     # compute random numbers between the mean, std and is_null
#     rand_10 = np.random.randint(mean10 - std10, mean10 + std10, size = is_null10)
#     rand_11 = np.random.randint(mean11 - std11, mean11 + std11, size = is_null11)
#     rand_13 = np.random.randint(mean13 - std13, mean13 + std13, size = is_null13)
#     rand_15 = np.random.randint(mean15 - std15, mean15 + std15, size = is_null15)
#     # fill NaN values in Age column with random values generated
#     var10_slice = dataset["VAR10"].copy()
#     var11_slice = dataset["VAR11"].copy()
#     var13_slice = dataset["VAR13"].copy()
#     var15_slice = dataset["VAR15"].copy()
#     var10_slice[np.isnan(var10_slice)] = rand_10
#     var11_slice[np.isnan(var11_slice)] = rand_11
#     var13_slice[np.isnan(var13_slice)] = rand_13
#     var15_slice[np.isnan(var15_slice)] = rand_15
#     dataset["VAR10"] = var10_slice
#     dataset["VAR11"] = var11_slice
#     dataset["VAR13"] = var13_slice
#     dataset["VAR15"] = var15_slice

In [0]:
# for dataset in data:
#     dataset['VAR6'] = dataset['VAR6'].fillna(train_df['VAR6'].describe()['mean'])
#     dataset['VAR3'] = dataset['VAR3'].fillna(train_df['VAR3'].describe()['mean'])
#     dataset['VAR2'] = dataset['VAR2'].fillna(train_df['VAR2'].describe()['mean'])
#     dataset['VAR16'] = dataset['VAR16'].fillna(train_df['VAR16'].describe()['mean'])
#     dataset['VAR8'] = dataset['VAR8'].fillna(train_df['VAR8'].describe()['mean'])
#     dataset['VAR7'] = dataset['VAR7'].fillna(train_df['VAR7'].describe()['mean'])
#     dataset['VAR5'] = dataset['VAR5'].fillna(train_df['VAR5'].describe()['mean'])

In [0]:
train_df = train_df.fillna(train_df.mean())
lead_df = lead_df.fillna(lead_df.mean())
eval_df = eval_df.fillna(eval_df.mean())

In [0]:
data = [train_df, lead_df, eval_df]
for dataset in data:
    dataset['VAR18'] = dataset['VAR18'].astype(float)
    dataset['VAR19'] = dataset['VAR19'].astype(float)

In [0]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34000 entries, 0 to 33999
Data columns (total 21 columns):
VAR1     34000 non-null int64
VAR2     34000 non-null float64
VAR3     34000 non-null float64
VAR4     34000 non-null float64
VAR5     34000 non-null float64
VAR6     34000 non-null float64
VAR7     34000 non-null float64
VAR8     34000 non-null float64
VAR9     34000 non-null float64
VAR10    34000 non-null float64
VAR11    34000 non-null float64
VAR12    34000 non-null float64
VAR13    34000 non-null float64
VAR14    34000 non-null object
VAR15    34000 non-null float64
VAR16    34000 non-null float64
VAR17    34000 non-null float64
VAR18    34000 non-null float64
VAR19    34000 non-null float64
VAR20    34000 non-null float64
VAR21    34000 non-null object
dtypes: float64(18), int64(1), object(2)
memory usage: 5.4+ MB

In [0]:
train_df['VAR14'].describe()

count     34000
unique       21
top           1
freq      20816
Name: VAR14, dtype: object

In [0]:
train_df = train_df.drop(['VAR14'], axis=1)
lead_df = lead_df.drop(['VAR14'], axis = 1)
eval_df = eval_df.drop(['VAR14'], axis = 1)

In [0]:
value = {"Low": 0.0, "Medium": 1.0, "High": 2.0}
data = [train_df]

for dataset in data:
    dataset['VAR21'] = dataset['VAR21'].map(value)

In [0]:
# Splting into train and test data

X = train_df.iloc[:, 0:19]
Y = train_df.loc[:, 'VAR21']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [0]:
# Normalizing X_train

names = X_train.columns
scaler = preprocessing.StandardScaler()

scaled_df = scaler.fit_transform(X_train)
scaled_df * 10
scaled_df = pd.DataFrame(scaled_df, columns = names)
X_train = scaled_df.round(4)

In [0]:
# Normalizing X_test

names = X_test.columns
scaler = preprocessing.StandardScaler()

scaled_testdf = scaler.fit_transform(X_test)
scaled_testdf * 10
scaled_testdf = pd.DataFrame(scaled_testdf, columns = names)
X_test = scaled_testdf.round(4)

In [0]:
# KNN Model

knn = KNeighborsClassifier(n_neighbors=80)
knn.fit(X_train, Y_train)

print(knn)

Y_pred = knn.predict(X_test)

print("Accuracy: ",  metrics.accuracy_score(Y_test, Y_pred))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=80, p=2,
                     weights='uniform')
Accuracy:  0.5380882352941176

In [0]:
# XGBoost Model

model1 = XGBClassifier()
model1.fit(X_train, Y_train)

print(model1)

Y_pred = model1.predict(X_test)
print(Y_pred)

print("Accuracy: ",  metrics.accuracy_score(Y_test, Y_pred))

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)
[1. 1. 1. ... 1. 1. 1.]
Accuracy:  0.5555882352941176

In [0]:
# Naive Bayes Classifier

model2 = GaussianNB()
model2.fit(X_train, Y_train)

print(model2)

Y_pred = model2.predict(X_test)

print("Accuracy: ",  metrics.accuracy_score(Y_test, Y_pred))

GaussianNB(priors=None, var_smoothing=1e-09)
Accuracy:  0.5076470588235295

In [0]:
# Random Forest Classifier Model

model3 = RandomForestClassifier(n_estimators = 3)
model3.fit(X_train, Y_train)

print(model3)

Y_pred = model3.predict(X_test)
print(Y_pred)

print("Accuracy: ",  metrics.accuracy_score(Y_test, Y_pred))

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=3,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
[1. 0. 1. ... 1. 1. 0.]
Accuracy:  0.4682352941176471

In [0]:
# Decision Tree Model using gini

model4 = DecisionTreeClassifier(criterion = "gini", random_state = 100, max_depth=4, min_samples_leaf=5)
model4.fit(X_train, Y_train)

print(model4)

Y_pred = model4.predict(X_test)

print("Accuracy: ",  metrics.accuracy_score(Y_test, Y_pred))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=100, splitter='best')
Accuracy:  0.5479411764705883

In [0]:
# Decision Tree Model using entropy

model5 = DecisionTreeClassifier(criterion = "entropy", random_state = 100, max_depth=6, min_samples_leaf=5)
model5.fit(X_train, Y_train)

print(model5)

Y_pred = model5.predict(X_test)

print("Accuracy: ",  metrics.accuracy_score(Y_test, Y_pred))

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=6,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=100, splitter='best')
Accuracy:  0.5519117647058823

In [0]:
# SGD Classifier

model6 = linear_model.SGDClassifier(max_iter=2000, tol=1e-3)
model6.fit(X_train, Y_train)

print(model6)

Y_pred = model6.predict(X_test)

print("Accuracy: ",  metrics.accuracy_score(Y_test, Y_pred))

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=2000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
Accuracy:  0.533235294117647

In [0]:
# Logistic Regression Classifier solver = 'saga' or 'sag' or 'newton-cg' or 'lbfgs'

model7 = LogisticRegression(random_state=0, solver='lbfgs', multi_class='multinomial')
model7.fit(X_train, Y_train)

print(model7)

Y_pred = model7.predict(X_test)

print("Accuracy: ",  metrics.accuracy_score(Y_test, Y_pred))

Y_pred

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
Accuracy:  0.5436764705882353

array([1., 1., 1., ..., 1., 1., 1.])

In [0]:
# Neural Network Model

model = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(6, 4, 2), activation='tanh', max_iter=300)
model.fit(X_train, Y_train)

print(model)

Y_pred = model.predict(X_test)

print("Accuracy: ",  metrics.accuracy_score(Y_test, Y_pred))

Y_pred

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(6, 4, 2), learning_rate='constant',
              learning_rate_init=0.001, max_iter=300, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='lbfgs', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)
Accuracy:  0.5657352941176471

array([0., 1., 1., ..., 1., 1., 1.])

In [0]:
Y_prediction = model.predict(lead_df)
data = Y_prediction
data = data.astype(int)
dat1 = [0]*len(data)
for dat in range(0,len(data)):
    if data[dat] == 0:
        dat1[dat] = 'Low'
    if data[dat] == 1:
        dat1[dat] = "Medium"
    if data[dat]== 2:
        dat1[dat] = "High"

In [0]:
X_test

        VAR1    VAR2    VAR3    VAR4  ...   VAR17   VAR18   VAR19   VAR20
0     1.2767 -0.6561 -0.0498  0.0053  ...  1.1726 -0.6068  1.5059  0.4060
1     1.2807  1.3307 -0.0654 -1.0976  ...  0.0053 -0.6068 -0.6641 -0.0339
2     1.4056 -1.0818 -0.0050  0.0053  ...  0.0053 -0.6068  1.5059  0.1959
3     0.5473  0.5502 -0.0702  0.0053  ...  0.0053 -0.6068  1.5059  0.4692
4    -1.1806 -1.2001 -0.0294  0.0053  ... -3.0514 -0.6068 -0.6641 -0.1313
5     0.4638  0.2427 -0.0634  0.0053  ...  0.0053 -0.6068 -0.6641 -0.4342
6     0.3383 -2.4773 -0.0685  2.7975  ... -4.4607  0.8700 -0.6641  0.3531
7    -1.3529 -0.1357  0.0966 -0.7267  ...  1.1522 -0.6068  1.5059 -0.5152
8     0.3652  0.6448 -0.0050  0.0053  ...  0.0053 -0.6068 -0.6641  0.3327
9     1.5751  0.1481 -0.0702  0.0153  ...  0.0053 -0.6068  1.5059 -0.4663
10    0.2776  0.8104 -0.0225  0.0053  ...  0.0053 -0.6068 -0.6641 -0.4785
11    0.6361  1.0705 -0.0651  0.0053  ...  0.0053 -0.6068 -0.6641 -0.4619
12   -0.1545  1.2598 -0.0600  0.0053  ...  0.0053  2.3468 -0.6641 -0.3097
13   -1.5455  1.3780 -0.0668  0.0053  ...  0.0053 -0.6068 -0.6641 -0.0765
14    0.4106 -1.6968 -0.0634  0.7572  ...  0.4326 -0.6068  1.5059  0.4739
15    1.1602  1.3071  0.0626  0.0053  ...  0.5574  0.8700  1.5059 -0.4073
16    0.5743 -0.6561 -0.0225  0.0053  ...  0.0053  0.8700 -0.6641  0.1530
17   -0.3282  0.7394 -0.0719  0.0053  ...  0.0053 -0.6068  1.5059 -0.4694
18   -0.0980  0.2664 -0.0225  0.0053  ...  0.0053  2.3468 -0.6641 -0.1801
19    0.6871  0.6685 -0.0639 -0.3557  ...  0.0246 -0.6068 -0.6641  0.6670
20   -1.6856 -1.6731  0.0455  0.7572  ...  1.0025 -0.6068 -0.6641 -0.5001
21   -1.1666  0.5029 -0.0651  0.2008  ...  1.1726 -0.6068 -0.6641 -0.5315
22    1.4903 -0.9163 -0.0668  0.9427  ...  0.0053 -0.6068 -0.6641  0.1204
23   -1.2338  0.2427 -0.0651  0.0053  ...  0.0053  2.3468 -0.6641  0.3694
24    0.5977 -1.5076 -0.0685  0.7572  ... -0.7797 -0.6068 -0.6641 -0.3777
25    1.3868 -1.7914 -0.0396  0.0153  ...  1.1726 -0.6068  1.5059  3.0132
26    0.1439 -0.8926 -0.0498  1.4992  ...  0.0053 -0.6068 -0.6641 -0.5833
27   -1.5328 -0.7270  0.0285  0.2008  ...  0.0053 -0.6068  1.5059 -0.6798
28    1.2225  0.0771 -0.0600  0.0153  ...  0.0053 -0.6068  1.5059 -0.3269
29   -0.7004 -0.8217 -0.0634  0.9427  ... -1.0132  2.3468 -0.6641  1.3621
...      ...     ...     ...     ...  ...     ...     ...     ...     ...
6770  0.7552  0.1008 -0.0695  0.0053  ...  1.1726 -0.6068 -0.6641 -0.4050
6771 -1.3108  1.3780 -0.0719  0.0053  ...  1.1726 -0.6068 -0.6641 -0.1926
6772  1.5277 -1.2711 -0.0050  0.0053  ...  0.0053 -0.6068 -0.6641 -0.2090
6773 -0.6508  1.2361  0.1307  0.0053  ...  0.0053  0.8700 -0.6641 -0.0961
6774 -0.9666  1.3544  0.0626 -1.0976  ...  0.9413 -0.6068 -0.6641 -0.5055
6775 -0.3665 -1.0345 -0.0634  1.8701  ... -0.8674 -0.6068  1.5059 -0.5194
6776  1.1817  0.5975 -0.0651 -1.0976  ...  1.0002  0.8700 -0.6641 -0.4650
6777  0.6123 -0.5378 -0.0634  0.0053  ...  0.0053 -0.6068  1.5059 -0.1016
6778 -1.2776 -1.3893 -0.0634  0.0153  ... -4.0257 -0.6068 -0.6641 -0.5142
6779 -0.9703  0.2664 -0.0719 -0.5412  ...  0.0053 -0.6068  1.5059 -0.4177
6780  1.6430  0.1008 -0.0716  0.0053  ...  0.0053  0.8700 -0.6641  1.0916
6781 -0.1810  0.9759 -0.0532  0.0053  ... -2.5149 -0.6068 -0.6641 -0.3819
6782 -0.7543  0.2191 -0.0600 -1.0976  ...  0.0053  0.8700 -0.6641 -0.0164
6783  1.1288  0.3137 -0.0498  0.0053  ...  0.0053  0.8700 -0.6641 -0.4476
6784 -0.1431 -1.0109 -0.0719  3.7250  ... -2.4527 -0.6068 -0.6641 -0.0924
6785 -1.2499 -0.3723 -0.0651  1.8701  ...  0.0053 -0.6068 -0.6641  2.3998
6786 -0.0779 -1.5785 -0.0634  3.5395  ...  0.9079 -0.6068  1.5059 -0.5682
6787 -1.1840  1.1178 -0.0464  0.0053  ...  0.0053  5.3003 -0.6641 -0.4885
6788  1.2749  0.5265 -0.0719  0.0153  ...  0.0053 -0.6068 -0.6641 -0.9236
6789 -0.4086  0.0535 -0.0702 -0.7267  ...  0.9864 -0.6068 -0.6641 -0.3236
6790  0.8641 -0.2067 -0.0668 -0.5412  ...  0.0053  0.8700 -0.6641  2.0641
6791  1.6503  0.9523 -0.0050  0.0053  ...  0.0053 -0.6068 -0.6641 -0.0284
6792 -0.2375 -2.4064 -0.0157  2.0556  ...  0.0053  0.8700 -0.6641  1.5533
6793  0.1270  0.7867 -0.0685  0.0053  ...  0.0053 -0.6068 -0.6641 -0.4367
6794  0.4505 -1.8624 -0.0685  2.0556  ...  0.0053 -0.6068 -0.6641  1.0290
6795  0.8354 -1.0345 -0.0668 -0.7267  ...  0.9999  0.8700 -0.6641 -0.3929
6796  1.3682 -1.5076 -0.0634  1.6846  ...  1.1726  0.8700 -0.6641 -0.4190
6797  0.7625  0.4792 -0.0729 -1.0976  ...  0.0053  0.8700 -0.6641 -0.5040
6798 -0.5807  0.7394 -0.0709  0.0053  ...  0.6526 -0.6068 -0.6641  0.1530
6799  1.1858 -0.2067 -0.0362 -0.7267  ...  0.0053 -0.6068 -0.6641 -0.4153

[6800 rows x 19 columns]

In [0]:
result = pd.DataFrame(dat1)

result.to_excel("leaders.xlsx", index = False)
files.download('leaders.xlsx')